# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.M_ClientCreateButton = QtWidgets.QPushButton(self.centralwidget)
        self.M_ClientCreateButton.setObjectName("M_ClientCreateButton")
        self.horizontalLayout.addWidget(self.M_ClientCreateButton)
        self.M_ServerOverviewButton = QtWidgets.QPushButton(self.centralwidget)
        self.M_ServerOverviewButton.setObjectName("M_ServerOverviewButton")
        self.horizontalLayout.addWidget(self.M_ServerOverviewButton)
        self.M_CreateKeyServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.M_CreateKeyServerButton.setObjectName("M_CreateKeyServerButton")
        self.horizontalLayout.addWidget(self.M_CreateKeyServerButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.M_ClientCreateButton.setText(_translate("MainWindow", "Create new client"))
        self.M_ServerOverviewButton.setText(_translate("MainWindow", "Server Overview"))
        self.M_CreateKeyServerButton.setText(_translate("MainWindow", "CreateKeyserver"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
