# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Serverwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerWind(object):
    def setupUi(self, ServerWind):
        ServerWind.setObjectName("ServerWind")
        ServerWind.resize(673, 478)
        self.gridLayout = QtWidgets.QGridLayout(ServerWind)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(ServerWind)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(ServerWind)
        QtCore.QMetaObject.connectSlotsByName(ServerWind)

    def retranslateUi(self, ServerWind):
        _translate = QtCore.QCoreApplication.translate
        ServerWind.setWindowTitle(_translate("ServerWind", "Form"))
